databases:
  - name: dms-db-prod-2026
    plan: free
    region: ohio

services:
  - type: web
    name: dms-unified-prod-2026
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: dms-db-prod-2026
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: dms-db-prod-2026
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: dms-db-prod-2026
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin_Sec#2026
      - key: REVIEWER_PASSWORD
        value: reviewer_Sec#2026
      - key: UPLOADER_PASSWORD
        value: uploader_Sec#2026
