databases:
  - name: dms-db-prod-2026
    plan: free

services:
  - type: web
    name: dms-unified-prod-2026
    env: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: dms-db-prod-2026
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dms-db-prod-2026
          property: port
      - key: DB_NAME
        fromDatabase:
          name: dms-db-prod-2026
          property: database
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: root
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin_Sec#2026
      - key: REVIEWER_PASSWORD
        value: reviewer_Sec#2026
      - key: UPLOADER_PASSWORD
        value: uploader_Sec#2026
